QS-366_ bugFixed
QDAP-DATAAI/qchat pull request #107
Opened 2024-06-12 07:40 UTC by SalehiElla

2024-06-13 02:26 UTC, kpqdap requested changes

2024-06-13 02:26 UTC, kpqdap commented on src/features/chat/chat-services/chat-translator-service.ts
> +
I would like an informational log event to show this occurring or not - so we can evaluate how frequently this would/will occur before approving

2024-06-16 23:45 UTC, SalehiElla commented on src/features/chat/chat-services/chat-translator-service.ts
> +
Added info logger.

2024-06-17 00:01 UTC, kpqdap approved these changes

2024-06-17 00:01 UTC, merged