implemented audio chat context
QDAP-DATAAI/qchat pull request #120
Opened 2024-06-24 05:48 UTC by qdap-bp

This pull request primarily focuses on introducing audio chat functionality to the chat services. It includes changes to the `chat-api-helper.ts` and `chat-api.ts` files in the `src/features/chat/chat-services/` directory. The most important changes are the addition of the `buildAudioChatMessages` function, the import of this function into `chat-api.ts`, and the integration of this function into the `ChatApi` function.

New Functionality:

* [`src/features/chat/chat-services/chat-api-helper.ts`](diffhunk://#diff-6d77056e441a1e3e83af3fb3c1d13c45e30a871dc6fe39be966b224dd004d3ffR10): Added the `FindAllChatDocumentsForCurrentUser` import and the `buildAudioChatMessages` function to handle audio chat messages. This function fetches all chat documents for the current user, builds the context from these documents, and returns the system and user messages along with the context. [[1]](diffhunk://#diff-6d77056e441a1e3e83af3fb3c1d13c45e30a871dc6fe39be966b224dd004d3ffR10) [[2]](diffhunk://#diff-6d77056e441a1e3e83af3fb3c1d13c45e30a871dc6fe39be966b224dd004d3ffR108-R147)

Codebase Updates:

* [`src/features/chat/chat-services/chat-api.ts`](diffhunk://#diff-165fc4d4be73e722a9fcc419023d14d90a99a578802a1516032500b86d3f6ac1L21-R26): Imported the `buildAudioChatMessages` function from `chat-api-helper.ts`.
* [`src/features/chat/chat-services/chat-api.ts`](diffhunk://#diff-165fc4d4be73e722a9fcc419023d14d90a99a578802a1516032500b86d3f6ac1L42-R48): Integrated the `buildAudioChatMessages` function into the `ChatApi` function to handle the case where `props.chatType` is "audio". This change also includes a minor update to the `translate` function. [[1]](diffhunk://#diff-165fc4d4be73e722a9fcc419023d14d90a99a578802a1516032500b86d3f6ac1L42-R48) [[2]](diffhunk://#diff-165fc4d4be73e722a9fcc419023d14d90a99a578802a1516032500b86d3f6ac1R59-L58)

2024-06-24 06:53 UTC, QDAP-Fred requested changes

2024-06-24 06:53 UTC, QDAP-Fred commented on src/features/chat/chat-services/chat-api.ts
> +    let translate: (input: string) => Promise<string> = async (_input: string): Promise<string> =>
[chore]: `translate` should be a `const` and initialise, something like :
```ts
const translate = await (input string, useTranslator = false) => {
  if(!useTranslator) return await Promise.resolve("")
  
  const translatedCompletion = await translator(input)
  return translatedCompletion.status === "OK" ? translatedCompletion.response : ""
}

// usage
const shouldUseTranslator = props.chatType === "simple" || !dataChatTypes.includes(props.chatType)
const translatedCompletion = await translate(completion, shouldUseTranslator)
```

2024-06-24 06:53 UTC, QDAP-Fred commented on src/features/chat/chat-services/chat-api-helper.ts
> +----------------\n
[fyi]: when using string interpolation, you don't need to put `\n` in the text

2024-06-24 11:03 UTC, kpqdap commented on src/features/chat/chat-services/chat-api-helper.ts
> +  const documents = await FindAllChatDocumentsForCurrentUser(chatThreadId)
@qdap-bp - let's just return the full transcript and add it into the message for context

2024-06-25 03:25 UTC, QDAP-Fred approved these changes

2024-06-25 03:25 UTC, merged