Feature/qggpt 375 flesch
QDAP-DATAAI/qchat pull request #53
Opened 2024-04-24 03:52 UTC by SalehiElla

Added Readability Score

2024-04-24 07:18 UTC, QDAP-Fred requested changes

2024-04-24 07:18 UTC, QDAP-Fred commented on src/components/chat/chat-row.tsx
> +          <Typography variant="h3" className="mt-0 flex-1 text-center text-heading" tabIndex={0}>
are we expecting to display to chatMessageId to everyone?

2024-04-24 07:18 UTC, QDAP-Fred commented on src/features/chat/chat-services/chat-flesch.ts
> +  const words = countWords(text)
Safety first! wrap it in a try-catch

2024-04-24 07:18 UTC, QDAP-Fred commented on src/features/chat/models.ts
> +  systemFleshScore?: number
use fleshScore property in ChatThreadModel

2024-04-24 07:18 UTC, QDAP-Fred commented on src/features/ui/assistant-buttons.tsx
> +              <strong>Readability Level:</strong> This test rates text on a 100-point scale.<br></br> The higher the
fyi `<br></br>` can be simplified with `<br />`

2024-04-26 03:52 UTC, SalehiElla commented on src/components/chat/chat-row.tsx
> +  const handleFleschIconClick = () => {}
Done

2024-04-26 03:52 UTC, SalehiElla commented on src/features/chat/chat-services/chat-flesch.ts
> +  const words = countWords(text)
all sorted

2024-04-26 03:53 UTC, SalehiElla commented on src/features/ui/assistant-buttons.tsx
> +              <strong>Readability Level:</strong> This test rates text on a 100-point scale.<br></br> The higher the
Thanks, applied.

2024-04-26 04:32 UTC, QDAP-Fred approved these changes

2024-04-26 04:33 UTC, merged